### ISSUE TITLE
No documentation for MattaMod Camera Module Mount for Prusa i3 MK3S (and BondTech)

### ISSUE THREAD

**Issue by tom-walkr** [Matta-Labs/camera-mounts#1]
I have added the STLs, but not got round to adding documentation. I will also add STEP files.

**Comment by Zarnack** [comment]
Hi,
is there an estimated timeframe for adding some documentation? Especially a link to the used camera module would be very appreciated!

**Comment by tom-walkr** [comment]
Hi! Apologies for the delay in writing up! I will set myself a goal to get documentation up in the next two weeks.

In the meantime - here is a link to the camera module we use with this mount:

https://www.aliexpress.us/item/3256804790797706.html?spm=a2g0o.order_list.order_list_main.11.7b211802XNQjSI&gatewayAdapt=glo2usa4itemAdapt

The 66°, Fixed Focus model is best for the job!

**Comment by tom-walkr** [comment]
@Zarnack Docs added. Apologies for roughness, will refine over time, but should be enough there to get you started! Will add images of the lighting installation tomorrow.
